<h1>Cadastrar</h1>


<form action="<?php echo $this->basePath('index/cadastrar'); ?>" method="POST">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" name="nome" id="nome" class="form-control" />
    </div>

    <div class="form-group">
        <label for="preco">Preço</label>
        <input type="text" name="preco" id="preco" class="form-control" />
    </div>

    <div class="form-group">
        <label for="descricao">Descrição</label>
        <input type="text" name="descricao" id="descricao" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary"/>
    </div>

</form>